[versions]
agp = "8.13.1"
kotlin = "2.2.21"

[libraries]
androidx-activity = "androidx.activity:activity:1.11.0"
androidx-webkit = "androidx.webkit:webkit:1.14.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

