[versions]
agp = "8.6.0-rc01"
kotlin = "1.9.21"

[libraries]
androidx-activity = "androidx.activity:activity:1.9.1"
androidx-webkit = "androidx.webkit:webkit:1.11.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

